# Generated by Django 3.0.3 on 2020-09-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('noticia', models.CharField(blank=True, max_length=255, null=True)),
                ('relacionadas', models.ManyToManyField(related_name='_carrera_relacionadas_+', to='main.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('noticia', models.CharField(blank=True, max_length=255, null=True)),
                ('carreras', models.ManyToManyField(related_name='universidadesSelf', to='main.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacion', models.CharField(max_length=64)),
                ('informacion', models.TextField()),
                ('carreras', models.ManyToManyField(related_name='orientacion', to='main.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tituloReseña', models.CharField(max_length=70, verbose_name='Titulo de la reseña')),
                ('reseña', models.TextField()),
                ('mostrarReseña', models.BooleanField()),
                ('recomendacion', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=1)),
                ('profesores', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=1)),
                ('exigencia', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=1)),
                ('cargaHoraria', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=1)),
                ('progIntercambio', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=1)),
                ('tiempoCarrera', models.PositiveSmallIntegerField(choices=[(1, 'Primer año'), (2, 'Segundo año'), (3, 'Tercer año'), (4, 'Cuarto año'), (5, 'Quinto año o más'), (6, 'Termine la carrera')], default=1)),
                ('nombre', models.CharField(max_length=70)),
                ('permitirContacto', models.BooleanField()),
                ('contacto', models.CharField(max_length=70)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinionesCar', to='main.Carrera')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinionesUni', to='main.Universidad')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='universidades',
            field=models.ManyToManyField(related_name='carrerasSelf', to='main.Universidad'),
        ),
    ]
