# Generated by Django 3.0.3 on 2020-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='abreviacion',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='contacto',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tiempoCarrera',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primer año'), (2, 'Segundo año'), (3, 'Tercer año'), (4, 'Cuarto año'), (5, 'Quinto año o más'), (6, 'Termine la carrera')], default=1, null=True),
        ),
    ]
