# Generated by Django 3.0.3 on 2020-09-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200904_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cargaHoraria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrella'), (3, 'Tres estrella'), (4, 'Cuatro estrella'), (5, 'Cinco estrella')], default=1),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='exigencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrella'), (3, 'Tres estrella'), (4, 'Cuatro estrella'), (5, 'Cinco estrella')], default=1),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='profesores',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrella'), (3, 'Tres estrella'), (4, 'Cuatro estrella'), (5, 'Cinco estrella')], default=1),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='progIntercambio',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrella'), (3, 'Tres estrella'), (4, 'Cuatro estrella'), (5, 'Cinco estrella')], default=1),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='recomendacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrella'), (3, 'Tres estrella'), (4, 'Cuatro estrella'), (5, 'Cinco estrella')], default=1),
        ),
    ]
