# Generated by Django 3.0.3 on 2020-09-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200904_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='orientaciones',
            field=models.ManyToManyField(blank=True, related_name='carreraDeOrientaciones', to='main.Orientacion'),
        ),
        migrations.AddField(
            model_name='orientacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universidad',
            name='orientaciones',
            field=models.ManyToManyField(blank=True, related_name='unisConOrientaciones', to='main.Orientacion'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='relacionadas',
            field=models.ManyToManyField(blank=True, related_name='_carrera_relacionadas_+', to='main.Carrera'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='universidadesSelf', to='main.Carrera'),
        ),
        migrations.CreateModel(
            name='Especificas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especifica', to='main.Carrera')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreraEspecifica', to='main.Universidad')),
            ],
        ),
    ]
