# Generated by Django 3.0.3 on 2020-09-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200907_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especificas',
            new_name='Especifica',
        ),
    ]
