# Generated by Django 3.0.3 on 2020-09-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200907_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='especifica',
            options={'ordering': ['carrera']},
        ),
        migrations.AlterModelOptions(
            name='orientacion',
            options={'ordering': ['orientacion']},
        ),
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['nombre']},
        ),
    ]
