# Generated by Django 3.0.3 on 2020-09-29 00:58

from django.db import migrations, models
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200922_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 29, 1, 5, 8, 301434, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='reseña',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tituloReseña',
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name='Titulo de la reseña'),
        ),
    ]
