# Generated by Django 3.0.3 on 2020-09-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200928_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='publicado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
