# Generated by Django 3.0.3 on 2020-09-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200928_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='publicado',
        ),
    ]
