# Generated by Django 3.0.3 on 2020-09-29 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_formulario_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 1, 5, 8, 301434, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
