# Generated by Django 3.0.3 on 2020-09-29 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_formulario_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='publicado',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
