# Generated by Django 3.0.3 on 2020-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200928_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='publicado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
