# Generated by Django 3.0.3 on 2020-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200928_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='mostrarReseña',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
